import {type Session} from 'next-auth';
import {SessionProvider} from 'next-auth/react';
import {type AppType} from 'next/app';
import {api} from '~/utils/api';
import '~/styles/globals.css';
import Head from 'next/head';
import Layout from '~/components/Layout';

const MyApp: AppType<{session: Session | null}> = ({
  Component,
  pageProps: {session, ...pageProps},
}) => {
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Rocklog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="icon"
          href="https://i.postimg.cc/44WH04kB/Screenshot-2023-06-13-at-5-45-40-PM.png"
        />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </SessionProvider>
  );
};

export default api.withTRPC(MyApp);
