import Head from 'next/head';
import Link from 'next/link';
import Layout from '~/components/Layout';
import {api} from '~/utils/api';

const Home = () => {
  return (
    <>
      <Head>
        <title>Rocklog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout></Layout>
      </main>
    </>
  );
};

export default Home;
