import {signIn, useSession} from 'next-auth/react';
import Head from 'next/head';
import {AiFillGithub} from 'react-icons/ai';
import {FcGoogle} from 'react-icons/fc';
import Button from '~/components/Buttons/Button';
import Layout from '~/components/Layout';
import LoginModal from '~/components/Modals/LoginModal';
import RegisterModal from '~/components/Modals/RegisterModal';
import {api} from '~/utils/api';

const Home = () => {
  return (
    <>
      <Head>
        <title>Rocklog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;

// const Content: React.FC = () => {
//   const {data: sessionData} = useSession();

//   const {data: posts, refetch: refetchPosts} = api.post.getAll.useQuery(
//     undefined,
//     {enabled: sessionData?.user !== undefined}
//   );

//   return <div>{JSON.stringify(posts)}</div>;
// };
